# Numpy란

Numeric + Python = Numpy(넘파이, 늄파이) 
수학 및 과학 연산을 위한 파이썬 패키지 
관련 사이트 : http://www.numpy.org 
리스트와의 차이점 : 하나의 데이터형만 지원 
np.array 함수를 활용하여 ndarray 배열을 생성함
아나콘다 설치 시 자동으로 설치

In [1]:
import numpy as np

In [3]:
list1  = [1,2,3,4,5]
list2 = [1,2,3,4,4.5]

In [4]:
arr1 = np.array(list1)

In [5]:
arr1 ## numpy array 로 변형 

array([1, 2, 3, 4, 5])

In [7]:
arr1.shape #numpy array shape 을 확인가능 


(5,)

In [8]:
arr2 = np.array(list2)
arr2 ## 실수형 numpy array shape 형태 

array([1. , 2. , 3. , 4. , 4.5])

In [9]:
print(arr1.dtype) # 타입 확인 

int64


In [10]:
print(arr2.dtype) # 타입확인 

float64


In [12]:
arr3 = np.array([[1,2,3],
                [4,5,6],
                [2,4,5]])

In [13]:
arr3.shape # 3행 3열 형태로 나타낼 수 있다. 

(3, 3)

In [14]:
np.zeros(10) # 0 이 10개인 numpy array 제작 가능 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros([3,3])
np.ones([3,3]) ## 모든숫자가 1인 3*3 행렬 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.array(range(1,11))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.arange(1,11) ## 위와 같은 역할 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Array 연산

In [23]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[10,11,21],
                [12,13,14]])


In [24]:
arr1 + arr2

array([[11, 13, 24],
       [16, 18, 20]])

In [26]:
arr1*arr2

array([[10, 22, 63],
       [48, 65, 84]])

#### 크기가 다른 array일때 

In [27]:
arr3 = np.array([10,11,12])

In [28]:
ㅇarr1 + arr3 # 같은행 끼리 더해주기 # 브로드캐스트 연사 가능

array([[11, 13, 15],
       [14, 16, 18]])

In [29]:
arr1 +10 ## 스칼라연산 가능

array([[11, 12, 13],
       [14, 15, 16]])

In [30]:
arr1**2 # 각 자리 제곱해서 보여준다 . 

array([[ 1,  4,  9],
       [16, 25, 36]])

# Array 인덱싱

In [31]:
arr1[0,0] ## 행과 열을 지정해서 인덱싱 가능하다 . 

1

In [32]:
arr1[-1,-1]

6

In [33]:
arr1[1:]

array([[4, 5, 6]])

In [35]:
arr1[:,1]

array([2, 5])

## bool 자료형 사용 

In [36]:
names = np.array(['aaa','bbb','cccc','asdda','eee'])

In [37]:
names

array(['aaa', 'bbb', 'cccc', 'asdda', 'eee'], dtype='<U5')

In [40]:
data = np.random.randn(5,4)

In [41]:
data #난수 발생할수 있다. 

array([[-0.34421706,  0.92917088,  0.8574579 , -1.09221662],
       [-2.21120207, -1.065318  , -0.69572648, -1.55912809],
       [-0.99899255,  0.75385003, -0.60187329, -0.50787143],
       [-0.66552875, -0.162301  ,  0.44496127, -0.69589346],
       [-0.07203587, -1.11017448,  0.12881923,  0.31011459]])

In [42]:
data[names == 'bbb', :]

array([[-2.21120207, -1.065318  , -0.69572648, -1.55912809]])

In [45]:
data[(names == 'bbb')| (names == 'asdda'), :]

array([[-2.21120207, -1.065318  , -0.69572648, -1.55912809],
       [-0.66552875, -0.162301  ,  0.44496127, -0.69589346]])

In [46]:
data[data[:,0]< 0,:] ## 

array([[-0.34421706,  0.92917088,  0.8574579 , -1.09221662],
       [-2.21120207, -1.065318  , -0.69572648, -1.55912809],
       [-0.99899255,  0.75385003, -0.60187329, -0.50787143],
       [-0.66552875, -0.162301  ,  0.44496127, -0.69589346],
       [-0.07203587, -1.11017448,  0.12881923,  0.31011459]])

In [48]:
data[data[:,0]< 0,2:4] = 0

In [49]:
data

array([[-0.34421706,  0.92917088,  0.        ,  0.        ],
       [-2.21120207, -1.065318  ,  0.        ,  0.        ],
       [-0.99899255,  0.75385003,  0.        ,  0.        ],
       [-0.66552875, -0.162301  ,  0.        ,  0.        ],
       [-0.07203587, -1.11017448,  0.        ,  0.        ]])

In [50]:
np.abs(data)## 내장함수 사용 절대값

array([[0.34421706, 0.92917088, 0.        , 0.        ],
       [2.21120207, 1.065318  , 0.        , 0.        ],
       [0.99899255, 0.75385003, 0.        , 0.        ],
       [0.66552875, 0.162301  , 0.        , 0.        ],
       [0.07203587, 1.11017448, 0.        , 0.        ]])

In [52]:
np.sqrt(data) # 제곱근을 못구하면 nan 값을 구한다.
data **0.5 # 동일한 값을 나타낸다.

/var/folders/ht/4d122qr50vs5jr5k781my7yr0000gn/T/ipykernel_93023/2269012879.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(data) # 제곱근을 못구하면 nan 값을 구한다.
/var/folders/ht/4d122qr50vs5jr5k781my7yr0000gn/T/ipykernel_93023/2269012879.py:2: RuntimeWarning: invalid value encountered in sqrt
  data **0.5


array([[       nan, 0.9639351 , 0.        , 0.        ],
       [       nan,        nan, 0.        , 0.        ],
       [       nan, 0.86824537, 0.        , 0.        ],
       [       nan,        nan, 0.        , 0.        ],
       [       nan,        nan, 0.        , 0.        ]])

In [53]:
np.square(data)

array([[0.11848538, 0.86335853, 0.        , 0.        ],
       [4.8894146 , 1.13490244, 0.        , 0.        ],
       [0.99798611, 0.56828986, 0.        , 0.        ],
       [0.44292851, 0.02634161, 0.        , 0.        ],
       [0.00518917, 1.23248737, 0.        , 0.        ]])

In [54]:
np.exp(data) # exp 함수 에 대입 

array([[0.70877507, 2.53240864, 1.        , 1.        ],
       [0.10956886, 0.34461825, 1.        , 1.        ],
       [0.36825025, 2.12516624, 1.        , 1.        ],
       [0.51400168, 0.85018526, 1.        , 1.        ],
       [0.93049752, 0.32950146, 1.        , 1.        ]])

In [55]:
np.log(data) # 자연로그에 대입했을때 

/var/folders/ht/4d122qr50vs5jr5k781my7yr0000gn/T/ipykernel_93023/182692439.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(data)
/var/folders/ht/4d122qr50vs5jr5k781my7yr0000gn/T/ipykernel_93023/182692439.py:1: RuntimeWarning: invalid value encountered in log
  np.log(data)


array([[        nan, -0.07346261,        -inf,        -inf],
       [        nan,         nan,        -inf,        -inf],
       [        nan, -0.28256183,        -inf,        -inf],
       [        nan,         nan,        -inf,        -inf],
       [        nan,         nan,        -inf,        -inf]])

In [56]:
np.log10(data)

/var/folders/ht/4d122qr50vs5jr5k781my7yr0000gn/T/ipykernel_93023/1570869634.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(data)
/var/folders/ht/4d122qr50vs5jr5k781my7yr0000gn/T/ipykernel_93023/1570869634.py:1: RuntimeWarning: invalid value encountered in log10
  np.log10(data)


array([[        nan, -0.03190441,        -inf,        -inf],
       [        nan,         nan,        -inf,        -inf],
       [        nan, -0.12271504,        -inf,        -inf],
       [        nan,         nan,        -inf,        -inf],
       [        nan,         nan,        -inf,        -inf]])

In [57]:
np.log2(data)

/var/folders/ht/4d122qr50vs5jr5k781my7yr0000gn/T/ipykernel_93023/2371420318.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(data)
/var/folders/ht/4d122qr50vs5jr5k781my7yr0000gn/T/ipykernel_93023/2371420318.py:1: RuntimeWarning: invalid value encountered in log2
  np.log2(data)


array([[        nan, -0.10598415,        -inf,        -inf],
       [        nan,         nan,        -inf,        -inf],
       [        nan, -0.40765056,        -inf,        -inf],
       [        nan,         nan,        -inf,        -inf],
       [        nan,         nan,        -inf,        -inf]])

In [58]:
np.sign(data) ## 양수 음수 확인 법 

array([[-1.,  1.,  0.,  0.],
       [-1., -1.,  0.,  0.],
       [-1.,  1.,  0.,  0.],
       [-1., -1.,  0.,  0.],
       [-1., -1.,  0.,  0.]])

In [60]:
np.ceil(data) ## 올림 하는 방법

array([[-0.,  1.,  0.,  0.],
       [-2., -1.,  0.,  0.],
       [-0.,  1.,  0.,  0.],
       [-0., -0.,  0.,  0.],
       [-0., -1.,  0.,  0.]])

In [62]:
np.floor(data) # 내림 하는 방법 

array([[-1.,  0.,  0.,  0.],
       [-3., -2.,  0.,  0.],
       [-1.,  0.,  0.,  0.],
       [-1., -1.,  0.,  0.],
       [-1., -2.,  0.,  0.]])

In [64]:
np.isnan(np.log2(data))

/var/folders/ht/4d122qr50vs5jr5k781my7yr0000gn/T/ipykernel_93023/1638304648.py:1: RuntimeWarning: divide by zero encountered in log2
  np.isnan(np.log2(data))
/var/folders/ht/4d122qr50vs5jr5k781my7yr0000gn/T/ipykernel_93023/1638304648.py:1: RuntimeWarning: invalid value encountered in log2
  np.isnan(np.log2(data))


array([[ True, False, False, False],
       [ True,  True, False, False],
       [ True, False, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False]])

In [66]:
data[np.isinf(np.log2(data))] = 1

/var/folders/ht/4d122qr50vs5jr5k781my7yr0000gn/T/ipykernel_93023/781355396.py:1: RuntimeWarning: divide by zero encountered in log2
  data[np.isinf(np.log2(data))] = 1
/var/folders/ht/4d122qr50vs5jr5k781my7yr0000gn/T/ipykernel_93023/781355396.py:1: RuntimeWarning: invalid value encountered in log2
  data[np.isinf(np.log2(data))] = 1


In [69]:
np.cos(data) ## 코싸인 적용하기 

array([[ 0.94133995,  0.59849841,  0.54030231,  0.54030231],
       [-0.59752084,  0.484226  ,  0.54030231,  0.54030231],
       [ 0.54114977,  0.72905912,  0.54030231,  0.54030231],
       [ 0.78659041,  0.98685808,  0.54030231,  0.54030231],
       [ 0.99740654,  0.44450523,  0.54030231,  0.54030231]])

In [70]:
arr1 = np.random.rand(5,3)

In [71]:
arr2 = np.random.rand(5,3)

In [73]:
np.add(arr1 ,arr2)

array([[1.05413998, 1.02578066, 0.59595659],
       [1.08191964, 1.21631183, 0.92333472],
       [1.35725911, 1.22739016, 0.61611277],
       [0.97163231, 1.34085444, 0.85012932],
       [1.02876865, 0.19539029, 0.75506221]])

In [74]:
np.multiply(arr1,arr2)

array([[0.27338492, 0.17475622, 0.05156017],
       [0.25548393, 0.2360661 , 0.08845311],
       [0.39919474, 0.36324369, 0.08733448],
       [0.23435082, 0.43243517, 0.17774302],
       [0.23811974, 0.00428709, 0.03357932]])

In [75]:
np.maximum(arr1,arr2)

array([[0.59353693, 0.81004394, 0.49093139],
       [0.73371252, 0.97392566, 0.81477306],
       [0.92630542, 0.72935821, 0.39502913],
       [0.5266392 , 0.80095495, 0.47925825],
       [0.67708497, 0.17020205, 0.70760748]])

In [76]:
np.minimum(arr1,arr2)

array([[0.46060306, 0.21573672, 0.1050252 ],
       [0.34820713, 0.24238616, 0.10856166],
       [0.43095369, 0.49803195, 0.22108364],
       [0.44499311, 0.53989949, 0.37087107],
       [0.35168369, 0.02518823, 0.04745473]])

In [77]:
arr1

array([[0.59353693, 0.81004394, 0.49093139],
       [0.73371252, 0.97392566, 0.10856166],
       [0.92630542, 0.72935821, 0.22108364],
       [0.5266392 , 0.53989949, 0.37087107],
       [0.35168369, 0.02518823, 0.04745473]])

# 전체 성분의 합

In [78]:
np.sum(arr1)

7.449195788203891

In [79]:
np.sum(arr1,axis = 1) ## 열간의 합 

array([1.89451226, 1.81619984, 1.87674727, 1.43740977, 0.42432665])

In [80]:
np.sum(arr1,axis = 0) ## 동일한 행간의 합 

array([3.13187775, 3.07841555, 1.2389025 ])

In [81]:
np.mean(arr1 , axis =0)

array([0.62637555, 0.61568311, 0.2477805 ])

In [82]:
np.std(arr1 , axis =0) #표준편차 

array([0.19388682, 0.32663841, 0.16401138])

In [83]:
np.var(arr1) # 분산 

0.08803936802774634

In [84]:
np.argmin(arr1) # 최솟값 표시 

13

In [85]:
np.argmax(arr1) # 최대값 위치 표시 

4

In [86]:
np.cumsum(arr1) # 누적합

array([0.59353693, 1.40358087, 1.89451226, 2.62822478, 3.60215044,
       3.7107121 , 4.63701752, 5.36637573, 5.58745937, 6.11409857,
       6.65399807, 7.02486914, 7.37655283, 7.40174106, 7.44919579])

In [87]:
np.cumprod(arr1) # 누적곱 

array([5.93536926e-01, 4.80790991e-01, 2.36035391e-01, 1.73182121e-01,
       1.68666512e-01, 1.83107160e-02, 1.69613155e-02, 1.23708747e-02,
       2.73499803e-03, 1.44035717e-03, 7.77648108e-04, 2.88407188e-04,
       1.01428103e-04, 2.55479469e-06, 1.21237093e-07])

In [88]:
np.sort(arr1) # 정렬 

array([[0.49093139, 0.59353693, 0.81004394],
       [0.10856166, 0.73371252, 0.97392566],
       [0.22108364, 0.72935821, 0.92630542],
       [0.37087107, 0.5266392 , 0.53989949],
       [0.02518823, 0.04745473, 0.35168369]])

In [89]:
np.sort(arr1)[::-1] # 정렬

array([[0.02518823, 0.04745473, 0.35168369],
       [0.37087107, 0.5266392 , 0.53989949],
       [0.22108364, 0.72935821, 0.92630542],
       [0.10856166, 0.73371252, 0.97392566],
       [0.49093139, 0.59353693, 0.81004394]])

In [92]:
np.sort(arr1,axis = 0) # 행간으로 오름차순 

array([[0.35168369, 0.02518823, 0.04745473],
       [0.5266392 , 0.53989949, 0.10856166],
       [0.59353693, 0.72935821, 0.22108364],
       [0.73371252, 0.81004394, 0.37087107],
       [0.92630542, 0.97392566, 0.49093139]])

# pandas 불러오기 


In [93]:
import pandas as pd

In [94]:
df = pd.read_csv('./data-4/gapminder.tsv' ,sep = '\t') ## tab 으로 구분자 tsv 

In [95]:
df

country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [96]:
df.head(5)

country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [97]:
df.tail(5)

country continent  year  lifeExp       pop   gdpPercap
1699  Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700  Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701  Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702  Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

In [98]:
type(df) ## 데이터 타입 확인하기 

pandas.core.frame.DataFrame

In [100]:
df.shape  # 행의 갯수 및 열의 갯수 확인 가능 

(1704, 6)

In [101]:
df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [102]:
df.dtypes # 각 columns 의 타입을 확인 할 수 있다. 

country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

In [103]:
df.info() # 조금더 df 파일을 확실이 알수 있다 . INDEX. 가 자동으로 만들어진다. 1704 가 아니면 결측치가 있을수 있다 . 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   country    1704 non-null   object 
 1   continent  1704 non-null   object 
 2   year       1704 non-null   int64  
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64  
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [104]:
df.describe() # 수치들을 확인 할 수 있다 . 최대 1사분위 2사분위 표준편차 

year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165876
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846988
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900

In [106]:
country_df  = df['country'] # column 명으로 선택가능 

In [107]:
type(country_df) ## Serises 형태로 가져온다. 

pandas.core.series.Series

In [109]:
country_df.tail() # 함수들도 적용가능 

1699    Zimbabwe
1700    Zimbabwe
1701    Zimbabwe
1702    Zimbabwe
1703    Zimbabwe
Name: country, dtype: object

In [112]:
subset =  df[['country' ,'continent' ,'year']]

In [113]:
subset

country continent  year
0     Afghanistan      Asia  1952
1     Afghanistan      Asia  1957
2     Afghanistan      Asia  1962
3     Afghanistan      Asia  1967
4     Afghanistan      Asia  1972
...           ...       ...   ...
1699     Zimbabwe    Africa  1987
1700     Zimbabwe    Africa  1992
1701     Zimbabwe    Africa  1997
1702     Zimbabwe    Africa  2002
1703     Zimbabwe    Africa  2007

[1704 rows x 3 columns]

In [114]:
df.loc[0] ## 행의 값을 Serise 로 추출 

country      Afghanistan
continent           Asia
year                1952
lifeExp           28.801
pop              8425333
gdpPercap     779.445314
Name: 0, dtype: object

In [115]:
df.loc[99] ## 행의 값을 Serise 로 추출 

country      Bangladesh
continent          Asia
year               1967
lifeExp          43.453
pop            62821884
gdpPercap    721.186086
Name: 99, dtype: object

In [117]:
df.loc[1]  # -1 값은 없기 떄문에 에러 밟생 

country      Afghanistan
continent           Asia
year                1957
lifeExp           30.332
pop              9240934
gdpPercap      820.85303
Name: 1, dtype: object

In [118]:
df.iloc[99]

country      Bangladesh
continent          Asia
year               1967
lifeExp          43.453
pop            62821884
gdpPercap    721.186086
Name: 99, dtype: object

In [119]:
df.iloc[-1] ## 인덱스 번호로 가능하다. iloc 는 -1 이 먹힌다 그래서 

country        Zimbabwe
continent        Africa
year               2007
lifeExp          43.487
pop            12311143
gdpPercap    469.709298
Name: 1703, dtype: object

In [120]:
df.loc[[0,99,999]] # 여러개의 행을 추출 가능 

country continent  year  lifeExp       pop    gdpPercap
0    Afghanistan      Asia  1952   28.801   8425333   779.445314
99    Bangladesh      Asia  1967   43.453  62821884   721.186086
999     Mongolia      Asia  1967   51.253   1149500  1226.041130

In [122]:
df[['year', 'pop']]

year       pop
0     1952   8425333
1     1957   9240934
2     1962  10267083
3     1967  11537966
4     1972  13079460
...    ...       ...
1699  1987   9216418
1700  1992  10704340
1701  1997  11404948
1702  2002  11926563
1703  2007  12311143

[1704 rows x 2 columns]

In [123]:
df.loc[:,['year','pop']]

year       pop
0     1952   8425333
1     1957   9240934
2     1962  10267083
3     1967  11537966
4     1972  13079460
...    ...       ...
1699  1987   9216418
1700  1992  10704340
1701  1997  11404948
1702  2002  11926563
1703  2007  12311143

[1704 rows x 2 columns]

In [125]:
df.iloc[:,[2,4]]
# df[[2,4]] # 인덱스 번호로는 힘들다

year       pop
0     1952   8425333
1     1957   9240934
2     1962  10267083
3     1967  11537966
4     1972  13079460
...    ...       ...
1699  1987   9216418
1700  1992  10704340
1701  1997  11404948
1702  2002  11926563
1703  2007  12311143

[1704 rows x 2 columns]

## 슬라이싱 

In [126]:
df.iloc[:,range(5)]

country continent  year  lifeExp       pop
0     Afghanistan      Asia  1952   28.801   8425333
1     Afghanistan      Asia  1957   30.332   9240934
2     Afghanistan      Asia  1962   31.997  10267083
3     Afghanistan      Asia  1967   34.020  11537966
4     Afghanistan      Asia  1972   36.088  13079460
...           ...       ...   ...      ...       ...
1699     Zimbabwe    Africa  1987   62.351   9216418
1700     Zimbabwe    Africa  1992   60.377  10704340
1701     Zimbabwe    Africa  1997   46.809  11404948
1702     Zimbabwe    Africa  2002   39.989  11926563
1703     Zimbabwe    Africa  2007   43.487  12311143

[1704 rows x 5 columns]

In [128]:
df.iloc[:,range(3,6)]

lifeExp       pop   gdpPercap
0      28.801   8425333  779.445314
1      30.332   9240934  820.853030
2      31.997  10267083  853.100710
3      34.020  11537966  836.197138
4      36.088  13079460  739.981106
...       ...       ...         ...
1699   62.351   9216418  706.157306
1700   60.377  10704340  693.420786
1701   46.809  11404948  792.449960
1702   39.989  11926563  672.038623
1703   43.487  12311143  469.709298

[1704 rows x 3 columns]

In [130]:
df.iloc[:,range(0,6,2)]

country  year       pop
0     Afghanistan  1952   8425333
1     Afghanistan  1957   9240934
2     Afghanistan  1962  10267083
3     Afghanistan  1967  11537966
4     Afghanistan  1972  13079460
...           ...   ...       ...
1699     Zimbabwe  1987   9216418
1700     Zimbabwe  1992  10704340
1701     Zimbabwe  1997  11404948
1702     Zimbabwe  2002  11926563
1703     Zimbabwe  2007  12311143

[1704 rows x 3 columns]

In [131]:
df.iloc[:,:3]

country continent  year
0     Afghanistan      Asia  1952
1     Afghanistan      Asia  1957
2     Afghanistan      Asia  1962
3     Afghanistan      Asia  1967
4     Afghanistan      Asia  1972
...           ...       ...   ...
1699     Zimbabwe    Africa  1987
1700     Zimbabwe    Africa  1992
1701     Zimbabwe    Africa  1997
1702     Zimbabwe    Africa  2002
1703     Zimbabwe    Africa  2007

[1704 rows x 3 columns]

In [132]:
df.iloc[:,0:6:2] ## 스탭으로  0 ,2 ,4 스탭으로 보여준다. 

country  year       pop
0     Afghanistan  1952   8425333
1     Afghanistan  1957   9240934
2     Afghanistan  1962  10267083
3     Afghanistan  1967  11537966
4     Afghanistan  1972  13079460
...           ...   ...       ...
1699     Zimbabwe  1987   9216418
1700     Zimbabwe  1992  10704340
1701     Zimbabwe  1997  11404948
1702     Zimbabwe  2002  11926563
1703     Zimbabwe  2007  12311143

[1704 rows x 3 columns]

In [133]:
df.iloc[:,: -1]

country continent  year  lifeExp       pop
0     Afghanistan      Asia  1952   28.801   8425333
1     Afghanistan      Asia  1957   30.332   9240934
2     Afghanistan      Asia  1962   31.997  10267083
3     Afghanistan      Asia  1967   34.020  11537966
4     Afghanistan      Asia  1972   36.088  13079460
...           ...       ...   ...      ...       ...
1699     Zimbabwe    Africa  1987   62.351   9216418
1700     Zimbabwe    Africa  1992   60.377  10704340
1701     Zimbabwe    Africa  1997   46.809  11404948
1702     Zimbabwe    Africa  2002   39.989  11926563
1703     Zimbabwe    Africa  2007   43.487  12311143

[1704 rows x 5 columns]

In [136]:
df.loc[10:13 ,['country' ,'lifeExp' ,'gdpPercap']]

country  lifeExp    gdpPercap
10  Afghanistan   42.129   726.734055
11  Afghanistan   43.828   974.580338
12      Albania   55.230  1601.056136
13      Albania   59.280  1942.284244

In [138]:
df.head(10) ## 앞의 행 10 가 확인 가능 # 각 연도별로 기대 수명 

country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106
5  Afghanistan      Asia  1977   38.438  14880372  786.113360
6  Afghanistan      Asia  1982   39.854  12881816  978.011439
7  Afghanistan      Asia  1987   40.822  13867957  852.395945
8  Afghanistan      Asia  1992   41.674  16317921  649.341395
9  Afghanistan      Asia  1997   41.763  22227415  635.341351

In [139]:
df.groupby('year')

In [140]:
df.groupby('year')['lifeExp'].mean()

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [142]:
df.groupby(['year','continent'])[['lifeExp','gdpPercap']].mean()

lifeExp     gdpPercap
year continent                         
1952 Africa     39.135500   1252.572466
     Americas   53.279840   4079.062552
     Asia       46.314394   5195.484004
     Europe     64.408500   5661.057435
     Oceania    69.255000  10298.085650
1957 Africa     41.266346   1385.236062
     Americas   55.960280   4616.043733
     Asia       49.318544   5787.732940
     Europe     66.703067   6963.012816
     Oceania    70.295000  11598.522455
1962 Africa     43.319442   1598.078825
     Americas   58.398760   4901.541870
     Asia       51.563223   5729.369625
     Europe     68.539233   8365.486814
     Oceania    71.085000  12696.452430
1967 Africa     45.334538   2050.363801
     Americas   60.410920   5668.253496
     Asia       54.663640   5971.173374
     Europe     69.737600  10143.823757
     Oceania    71.310000  14495.021790
1972 Africa     47.450942   2339.615674
     Americas   62.394920   6491.334139
     Asia       57.319269   8187.468699
     Europe     70.775033  12479.575246
     Oceania    71.910000  16417.333380
1977 Africa     49.580423   2585.938508
     Americas   64.391560   7352.007126
     Asia       59.610556   7791.314020
     Europe     71.937767  14283.979110
     Oceania    72.855000  17283.957605
1982 Africa     51.592865   2481.592960
     Americas   66.228840   7506.737088
     Asia       62.617939   7434.135157
     Europe     72.806400  15617.896551
     Oceania    74.290000  18554.709840
1987 Africa     53.344788   2282.668991
     Americas   68.090720   7793.400261
     Asia       64.851182   7608.226508
     Europe     73.642167  17214.310727
     Oceania    75.320000  20448.040160
1992 Africa     53.629577   2281.810333
     Americas   69.568360   8044.934406
     Asia       66.537212   8639.690248
     Europe     74.440100  17061.568084
     Oceania    76.945000  20894.045885
1997 Africa     53.598269   2378.759555
     Americas   71.150480   8889.300863
     Asia       68.020515   9834.093295
     Europe     75.505167  19076.781802
     Oceania    78.190000  24024.175170
2002 Africa     53.325231   2599.385159
     Americas   72.422040   9287.677107
     Asia       69.233879  10174.090397
     Europe     76.700600  21711.732422
     Oceania    79.740000  26938.778040
2007 Africa     54.806038   3089.032605
     Americas   73.608120  11003.031625
     Asia       70.728485  12473.026870
     Europe     77.648600  25054.481636
     Oceania    80.719500  29810.188275

In [144]:
df.groupby('continent')[['country']].nunique() # 대괄호 하나면 series  두개면 dataframe 형식응로  만들어진다.

country
continent         
Africa          52
Americas        25
Asia            33
Europe          30
Oceania          2